// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGKbnXNHgGBVV2XgQYo1uqMhmpOMaQbv4',
    appId: '1:1062127578849:web:89ddae1bcd2c76e4fa91a0',
    messagingSenderId: '1062127578849',
    projectId: 'cric11-442ef',
    authDomain: 'cric11-442ef.firebaseapp.com',
    storageBucket: 'cric11-442ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-9F7R4knVblG83Ze36OPC1idNaiST78s',
    appId: '1:1062127578849:android:801f2556c30b642bfa91a0',
    messagingSenderId: '1062127578849',
    projectId: 'cric11-442ef',
    storageBucket: 'cric11-442ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-2pTRegGVqnJ6jPkQM55a5lottdQjoE',
    appId: '1:1062127578849:ios:91c54e54252d904ffa91a0',
    messagingSenderId: '1062127578849',
    projectId: 'cric11-442ef',
    storageBucket: 'cric11-442ef.appspot.com',
    iosBundleId: 'com.seesea.cric11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-2pTRegGVqnJ6jPkQM55a5lottdQjoE',
    appId: '1:1062127578849:ios:43a6c8b948529b87fa91a0',
    messagingSenderId: '1062127578849',
    projectId: 'cric11-442ef',
    storageBucket: 'cric11-442ef.appspot.com',
    iosBundleId: 'com.seesea.cric11.RunnerTests',
  );
}
