// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrm6121_m_SQzS1_QMfOC07juOM6x0-VQ',
    appId: '1:22997878676:web:51a0f99563e7596396f181',
    messagingSenderId: '22997878676',
    projectId: 'cric11new-92409',
    authDomain: 'cric11new-92409.firebaseapp.com',
    storageBucket: 'cric11new-92409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPhsYnB33PFCKis0Adv1IS3jYf0OeDYw',
    appId: '1:22997878676:android:7d00e535b34f880896f181',
    messagingSenderId: '22997878676',
    projectId: 'cric11new-92409',
    storageBucket: 'cric11new-92409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB922FD0o_mLZ0JqUHHv1mJ_sYgNkGBuOA',
    appId: '1:22997878676:ios:bfcc9f2c108181fa96f181',
    messagingSenderId: '22997878676',
    projectId: 'cric11new-92409',
    storageBucket: 'cric11new-92409.appspot.com',
    iosBundleId: 'com.seesea.cric11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB922FD0o_mLZ0JqUHHv1mJ_sYgNkGBuOA',
    appId: '1:22997878676:ios:9f9380ae9876293096f181',
    messagingSenderId: '22997878676',
    projectId: 'cric11new-92409',
    storageBucket: 'cric11new-92409.appspot.com',
    iosBundleId: 'com.seesea.cric11.RunnerTests',
  );
}
